# DATAFRAME PRACTICE

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Creating a dataframe from a dictionary
data_dict = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 28],
    "City": ["New York", "London", "Tokyo"]
}

In [ ]:
pd.DataFrame(data_dict)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   28     Tokyo

In [ ]:
df1 = pd.DataFrame(data_dict)

In [ ]:
print("DataFrame from Dictionary:\n", df1)
print("-" * 30)

DataFrame from Dictionary:
       Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   28     Tokyo
------------------------------

In [ ]:
# Creating a dataframe from a list of lists
data_list = [["Alice", 25, "New York"],
             ["Bob", 30, "London"],
             ["Charlie", 28, "Tokyo"]]

In [ ]:
df2 = pd.DataFrame(data_list, columns=["Name", "Age", "City"])

In [ ]:
df2

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   28     Tokyo

In [ ]:
print("DataFrame from List of Lists:\n", df2)
print("-" * 30)

DataFrame from List of Lists:
       Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   28     Tokyo
------------------------------

In [ ]:
# Creating dataframe from Numpy Array
array_data = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

In [ ]:
df3 = pd.DataFrame(array_data, ["A", "B", "C"])

In [ ]:
print("DataFrame from Numpy:\n", df3)

DataFrame from Numpy:
    0  1  2
A  1  2  3
B  4  5  6
C  7  8  9

In [ ]:
# Inspecting Dataframes
print("Column labels:", df1.columns.tolist())
print("Row labels:", df1.index.tolist())
print("Data types of each column:\n", df1.dtypes)
print("Shape(rows and columns):", df1.shape)
print("Number of dimensions:", df1.ndim)

Column labels: ['Name', 'Age', 'City']
Row labels: [0, 1, 2]
Data types of each column:
 Name    object
Age      int64
City    object
dtype: object
Shape(rows and columns): (3, 3)
Number of dimensions: 2

In [ ]:
# Manipulating Dataframes
import numpy as np

In [ ]:
data = {
     'Product': ['A', 'B', 'A', 'C', 'B', 'A', 'C'],
    'Sales': [150, 200, 175, 300, 220, 180, 350],
    'Region': ['North', 'South', 'East', 'West', 'North', 'East', 'West']
}
df = pd.DataFrame(data)

In [ ]:
print("Our working Dataframe:\n", df)
print("-" * 30)

Our working Dataframe:
   Product  Sales Region
0       A    150  North
1       B    200  South
2       A    175   East
3       C    300   West
4       B    220  North
5       A    180   East
6       C    350   West
------------------------------

In [ ]:
# Get the first 3 rows and last 3 rows
df.head(3)

  Product  Sales Region
0       A    150  North
1       B    200  South
2       A    175   East

In [ ]:
df.tail(3)

  Product  Sales Region
4       B    220  North
5       A    180   East
6       C    350   West

In [ ]:
# Summary of the Dataframe
df.info(data) # Or df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  7 non-null      object
 1   Sales    7 non-null      int64
 2   Region   7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [ ]:
# Statistical summary
df.describe()

            Sales
count    7.000000
mean   225.000000
std     73.086706
min    150.000000
25%    177.500000
50%    200.000000
75%    260.000000
max    350.000000

In [ ]:
# Groupby
print("Total Sales per Product:\n", df.groupby("Product")["Sales"].sum())

Total Sales per Product:
 Product
A    505
B    420
C    650
Name: Sales, dtype: int64

In [ ]:
print("Average Sales Per Region", df.groupby("Region")["Sales"].mean())

Average Sales Per Region Region
East     177.5
North    185.0
South    200.0
West     325.0
Name: Sales, dtype: float64

In [ ]:
# Sort the Dataframe
print("Sort by Sales(descending):\n", df.sort_values(by="Sales", ascending=False))
print("-" * 30)

Sort by Sales(descending):
   Product  Sales Region
6       C    350   West
3       C    300   West
4       B    220  North
1       B    200  South
5       A    180   East
2       A    175   East
0       A    150  North
------------------------------

In [ ]:
# Using .isna() and .dropna(): Handle missing data
df_with_nan = df.copy()
df_with_nan.loc[0, "Sales"] = np.nan #set first sale to NaN

In [ ]:
print("Dataframe with a Nan:\n", df_with_nan)

Dataframe with a Nan:
   Product  Sales Region
0       A    NaN  North
1       B  200.0  South
2       A  175.0   East
3       C  300.0   West
4       B  220.0  North
5       A  180.0   East
6       C  350.0   West

In [ ]:
print("Check for Nan:\n", df_with_nan.isna())
print("\nDrop rows with any Nan:\n", df_with_nan.dropna())

Check for Nan:
    Product  Sales  Region
0    False   True   False
1    False  False   False
2    False  False   False
3    False  False   False
4    False  False   False
5    False  False   False
6    False  False   False

Drop rows with any Nan:
   Product  Sales Region
1       B  200.0  South
2       A  175.0   East
3       C  300.0   West
4       B  220.0  North
5       A  180.0   East
6       C  350.0   West