In [3]:
# Load Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Load Data
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()

# Clean Data
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

c:\Users\dell\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
# df[pd.notna(df["salary_year_avg"])]["salary_year_avg"]

In [5]:
# help(df.apply)

In [6]:
df_salary = df[pd.notna(df["salary_year_avg"])].copy()

def projected_salary(salary):
    return salary * 1.03

df_salary["salary_year_avg"].apply(projected_salary)

28        112785.00
77        144200.00
92        123600.00
100       235068.66
109        91670.00
            ...
785624    143392.48
785641    154500.00
785648    228531.25
785682    162225.00
785692    162225.00
Name: salary_year_avg, Length: 22003, dtype: float64

In [7]:
# Comparing how the new salary compares to the original salary
df_salary["salary_year_inflated"] = df_salary["salary_year_avg"].apply(projected_salary)

df_salary[["salary_year_avg", "salary_year_inflated"]].head(10)

     salary_year_avg  salary_year_inflated
28          109500.0             112785.00
77          140000.0             144200.00
92          120000.0             123600.00
100         228222.0             235068.66
109          89000.0              91670.00
116         114000.0             117420.00
146         129500.0             133385.00
180          90250.0              92957.50
212         157500.0             162225.00
257         103128.0             106221.84

In [8]:
# Using a lambda function to solve the same problem
df_salary["salary_year_inflated"] = df_salary["salary_year_avg"].apply(lambda salary: salary * 1.03)

df_salary[["salary_year_avg", "salary_year_inflated"]].head(10)

     salary_year_avg  salary_year_inflated
28          109500.0             112785.00
77          140000.0             144200.00
92          120000.0             123600.00
100         228222.0             235068.66
109          89000.0              91670.00
116         114000.0             117420.00
146         129500.0             133385.00
180          90250.0              92957.50
212         157500.0             162225.00
257         103128.0             106221.84

In [9]:
# Straight forward way
df_salary["salary_year_inflated"] = df_salary["salary_year_avg"] * 1.03

df_salary[["salary_year_avg", "salary_year_inflated"]].head(10)

     salary_year_avg  salary_year_inflated
28          109500.0             112785.00
77          140000.0             144200.00
92          120000.0             123600.00
100         228222.0             235068.66
109          89000.0              91670.00
116         114000.0             117420.00
146         129500.0             133385.00
180          90250.0              92957.50
212         157500.0             162225.00
257         103128.0             106221.84

### Application of apply method

In [20]:
df_new = df.copy()  # Creating a copy of the df to manipulate

In [21]:
indices = list(range(len(df)))  # Convert to list of indices

In [22]:
indices.remove(0)   # remove first index(0) and insert it at position 14
indices.insert(14, 0)

In [23]:
# Reorder the dataframe
df_new_reordered = df_new.iloc[indices].reset_index(drop=True)

In [27]:
type(df_new_reordered["job_skills"][0])

str

In [65]:
import ast

In [66]:
# Converting the string to a list using the ast module
ast.literal_eval(df["job_skills"][1])

ValueError: malformed node or string: []

In [63]:
type(df["job_skills"][1])

list

In [41]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)
    
df["job_skills"] = df["job_skills"].apply(clean_list)

In [42]:
type(df["job_skills"][1])

list

In [62]:
df["job_skills"][1]

[]

In [67]:
# Re writing the clean_list func to a lambda func
df["job_skills"] = df["job_skills"].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list)

ValueError: The truth value of an empty array is ambiguous. Use `array.size > 0` to check that an array is not empty.

In [69]:
df["job_skills"][1]

[]

### Calculate projected salary next year
- Senior roles assume 5%
- Other roles assume 3%

In [ ]:
df_salary["salary_year_inflated"] = df_salary["salary_year_avg"].apply(lambda salary: salary * 1.03)

df_salary[["salary_year_avg", "salary_year_inflated"]]

In [70]:
def projected_salary(row):
    if "Senior" in row["job_title_short"]:
        return 1.05 * row["salary_year_avg"]
    else:
        return 1.03 * row["salary_year_avg"]

df_salary["salary_year_inflated"] = df_salary.apply(projected_salary, axis=1)

df_salary[["job_title_short", "salary_year_avg", "salary_year_inflated"]]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]

In [75]:
# Checking is code worked by filtering for senior roles
df_salary.loc[
    df_salary['job_title_short'].str.startswith("Senior"),
    ["job_title_short", "salary_year_avg", "salary_year_inflated"]
]

              job_title_short  salary_year_avg  salary_year_inflated
495      Senior Data Engineer         168500.0            176925.000
573      Senior Data Engineer         160000.0            168000.000
657      Senior Data Engineer         165000.0            173250.000
726      Senior Data Engineer         173500.0            182175.000
733      Senior Data Engineer         160000.0            168000.000
...                       ...              ...                   ...
784947   Senior Data Engineer         150000.0            157500.000
785106   Senior Data Engineer         125000.0            131250.000
785132  Senior Data Scientist          99150.0            104107.500
785330  Senior Data Scientist         200935.5            210982.275
785340  Senior Data Scientist         196800.0            206640.000

[4412 rows x 3 columns]

In [77]:
# Using the lambda function
df_salary["salary_year_inflated"] = df_salary.apply(lambda row: 1.05 * row["salary_year_avg"] if "Senior" in row["job_title_short"] else 1.03 * row["salary_year_avg"], axis=1)

df_salary[["job_title_short", "salary_year_avg", "salary_year_inflated"]]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]